video-area: drop dup include outside GDK_WINDOWING_X11 after 02c1e86
Missing when Gtk4 is built without X11.

src/celluloid-video-area.c:28:10: fatal error: 'gdk/x11/gdkx.h' file not found
 #include <gdk/x11/gdkx.h>
          ^~~~~~~~~~~~~~~~